### ISSUE TITLE
Segmentation Fault when processing yaml file

### ISSUE THREAD

**Issue by Rwardc** [yahoo/proxy-verifier#291]
When processing this yaml file (which may be malformed), a segfault is encountered in `verifier_server.cc`:

```
meta:
  version: '1.0'


sessions:
  - protocol: [ { name: tcp }, {name: ip} ]
    transactions:
    - client-request:
        method: GET
        url: http://127.0.0.1
        version: '1.1'
        headers:
        fields:
          - [ Host, 127.0.0.1:8080 ]
          - [ Connection, Keep-Alive ]
          - [ uuid, the-transaction ]
        content:
          size: 0
      uuid: first-transaction

  
    proxy-response:
      content:
        encoding: plain
        size: 0
      headers:
        fields:
        - [ Connection, keep-alive ]
      reason: OK
      status: 200

```
Segfault output from gdb:

```
(gdb) run run --listen-http 127.0.0.1:8080 /c/Code/git/verifier-tests/simple.yaml
Starting program: /mnt/c/Code/git/proxy-verifier/bin/verifier-server run --listen-http 127.0.0.1:8080 /c/Code/git/verifier-tests/simple.yaml
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
ServerReplayFileHandler::txn_close (this=0x7ffffffebf00) at local/src/server/verifier-server.cc:547
547             _txn_node->Mark().line);
```

**Expected Behavior:**
Even when processing a bad yaml file, an informative error should be printed instead.
