### ISSUE TITLE
replay_gen.py does not fill `url` field even with valid url list file

### ISSUE THREAD

**Issue by Rwardc** [yahoo/proxy-verifier#294]
I'm not exactly sure if I'm doing something wrong, but I've created a url list file, a very simple one with a single url, and am feeding it to `replay_gen.py`. The output test files look reasonably formed, except that the `url` field in each transaction is empty. However, the `Host` field is populated with the url. The curious thing is that if I give the generator script a garbage url that's badly formed, the url field is then properly populated with the garbage. So for example:

Properly formed URL list file:
```
http://127.0.0.1:8080
```
Output test yaml file example:
```
    client-request:
      method: GET
      scheme: http
      url: ''
      version: '1.1'
      headers:
        fields:
        - [Host, 127.0.0.1:8080]
      content:
        encoding: plain
        size: 0
```
Bad URL list file:
```
this is garbage
```
And the corresponding output:
```
    client-request:
      method: GET
      scheme: http
      url: this is garbage
      version: '1.1'
      headers:
        fields:
        - [Host, '']
      content:
        encoding: plain
        size: 0
```
Maybe my url list file is not properly formatted? Any help would be appreciated.
