### ISSUE TITLE
Allo empty proxy-(request|response) elements

### ISSUE THREAD

**Issue by bneradt** [yahoo/proxy-verifier#3]
If the user does not require verification, then Proxy Verifier should not require populated proxy-request and proxy-response elements in the reply file. In other words, we should be able to do this:

```
meta:
  version: "1.0"

sessions:
- protocol: [ ipv4, tcp ]
  transactions:
  - all:
      headers:
        fields:
        - [ uuid, 1 ]

    client-request:
      version: "1.1"
      scheme: "http"
      method: "GET"
      url: "/path/1"
      headers:
        fields:
        - [ Host, example.one ]

    proxy-request:

    server-response:
      status: 200
      reason: OK
      content:
        size: 16
      headers:
        fields:
        - [ Content-Type, text/html ]
        - [ Content-Length, 16 ]

    proxy-response:
```

This currently does not work because the parser requires a method and status element in the proxy-request and proxy-response, respectively. A deep function used by processing both requests and responses uses these to determine whether it is parsing a request or a response. But this context could, instead, but passed down from above and doing so would create a more convenient user experience.
