### ISSUE TITLE
Multi-value fields verification issue

### ISSUE THREAD

**Issue by lzx404243** [yahoo/proxy-verifier#309]
The latest Proxy Verifier(v2.12.0) seems to have issue in verification for multi-value fields(such as `set-cookie` ). This can be demonstrated via the follow replay file snippet:
```yaml
        server-response:
          ...
          headers:
            fields:
              ...
              - [Set-Cookie, "B1=abc"]
              - [Set-Cookie, "B2=abc"]

        proxy-response:
          ...
          headers:
            fields:
              - [Set-Cookie, { value: B1= , as: contains }]
              - [Set-Cookie, { value: B2= , as: contains }]
   ```
The expectation is that the above should pass verification, since the server sends those `Set-cookie` fields and (from the logs) clients got both of them.
