### ISSUE TITLE
Add HTTP/2 Frame Flags support

### ISSUE THREAD

**Issue by masaori335** [yahoo/proxy-verifier#329]
Feature request: it'd great if HTTP/2 frame flags can be configured to test edge cases, 

- e.g.
```
  transactions:
  - client-request:
      frames:
      - HEADERS:
          flags:
            END_HEADERS: true
            END_STREAM: false
      - DATA:
          flags:
            END_STREAM: true
```

For now, it's automatically set
https://github.com/yahoo/proxy-verifier/blob/master/local/src/core/http2.cc#L1510-L1520
