### ISSUE TITLE
Add verification capability concerning duplicate fields

### ISSUE THREAD

**Issue by bneradt** [yahoo/proxy-verifier#5]
We currently support field verification for unique fields in a message, but not for duplicated fields (e.g., responses with two set-cookie fields).

SolidWallOfCode commented:

> Thinking a bit more on this, we may want a notation to explicit check for duplicates and pass / fail on that basis (e.g., having multiple Host fields is broken, but multiple Via isn't, but we might want to check that Via is getting split or not as part of the test).

> I think I favor using a list notation. This carries over to providing multiple fields to be sent. E.g.

```
set-cookie: [ "cookie1", "cookie2", "cookie3" ]
```

**Comment by bneradt** [comment]
This verifications like this can be done now:

```yaml
    proxy-response:
      status: 200 
      headers:
        fields:
        - [ set-cookie, [ "cookie1", "cookie2" ], equal ]

```
